### PR TITLE
Add some linter fixes

### PR DESCRIPTION
**Pull request by koolzz**
Just some minor linter fixes, might merge after big PRs so we have a clean realease

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] Waaait a bit maybe

## Test Plan:
CI needs to say Linter passed

## Review: 
Test in production

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Another CI run in progress, please try again in 15 minutes

**Comment by koolzz** [comment]
@onvm a bit better?

**Comment by onvm** [comment]
> @onvm a bit better?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm a bit better?

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35184636

## Linter Failed

examples/flow_table/openflow.h:50:  Using deprecated casting style.  Use static_cast<int>(...) instead  [readability/casting] [4]
examples/flow_table/openflow.h:569:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:634:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:771:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:804:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:865:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:926:  Extra space before ( in function call  [whitespace/parens] [4]
Total errors found: 7
onvm/onvm_mgr/onvm_init.c:107:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
onvm/onvm_mgr/onvm_init.c:114:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
onvm/onvm_mgr/onvm_init.c:116:  { should almost always be at the end of the previous line  [whitespace/braces] [4]
Total errors found: 3
onvm/onvm_mgr/onvm_pkt.c:68:  Are you taking an address of a cast?  This is dangerous: could be a temp var.  Take the address before doing the cast, rather than after  [runtime/casting] [4]
Total errors found: 1
onvm/onvm_nflib/onvm_common.h:366:  #endif line should be "#endif  // _ONVM_COMMON_H_"  [build/header_guard] [5]
Total errors found: 1
onvm/onvm_nflib/onvm_config_common.h:208:  #endif line should be "#endif  // _ONVM_CONFIG_COMMON_H_"  [build/header_guard] [5]
Total errors found: 1
onvm/onvm_nflib/onvm_nflib.c:523:  Line ends in whitespace.  Consider deleting these extra spaces.  [whitespace/end_of_line] [4]
Total errors found: 1
onvm/onvm_nflib/onvm_pkt_common.c:98:  Are you taking an address of a cast?  This is dangerous: could be a temp var.  Take the address before doing the cast, rather than after  [runtime/casting] [4]
Total errors found: 1
onvm/onvm_nflib/onvm_sc_mgr.h:79:  #endif line should be "#endif  // _ONVM_SC_MGR_H_"  [build/header_guard] [5]
Total errors found: 1

**Comment by kevindweb** [comment]
Do you want help making some of these fixes?

**Comment by koolzz** [comment]
> Do you want help making some of these fixes?

Sure, if you want to contribute just submit a pr to my branch and I'll quickly merge it so it appears here

**Comment by dennisafa** [comment]
@onvm hi

**Comment by onvm** [comment]
> @onvm hi

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm hi

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35142347

## Linter Failed

examples/flow_table/openflow.h:50:  Using deprecated casting style.  Use static_cast<int>(...) instead  [readability/casting] [4]
examples/flow_table/openflow.h:569:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:634:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:771:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:804:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:865:  Extra space before ( in function call  [whitespace/parens] [4]
examples/flow_table/openflow.h:926:  Extra space before ( in function call  [whitespace/parens] [4]
Total errors found: 7
onvm/onvm_mgr/onvm_pkt.c:68:  Are you taking an address of a cast?  This is dangerous: could be a temp var.  Take the address before doing the cast, rather than after  [runtime/casting] [4]
Total errors found: 1
onvm/onvm_nflib/onvm_pkt_common.c:98:  Are you taking an address of a cast?  This is dangerous: could be a temp var.  Take the address before doing the cast, rather than after  [runtime/casting] [4]
Total errors found: 1

**Pull request merged**
