### PR TITLE
Stats alignment fixes

### PR DESCRIPTION
**Pull request by koolzz**
Fixes a few stats alignment issues

## Summary:
 - Tag wasn't properly null terminated when length was more than max size
 - Stats totals were misaligned 

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Another CI run in progress, please try again in 15 minutes

**Comment by kevindweb** [comment]
@onvm let's get it

**Comment by onvm** [comment]
> @onvm let's get it

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvmTest this should work too

**Comment by kevindweb** [comment]
@onvmTest great

**Comment by kevindweb** [comment]
@onvmTest api call

**Comment by onvm** [comment]
> @onvmTest api call

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm are we back up now?

**Comment by onvm** [comment]
> @onvm are we back up now?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm are we back up now?

## CI Message

Error: ERROR: Failed to copy ONVM files to nimbnode30


## Linter Output

onvm/onvm_mgr/onvm_stats.h:63:  Lines should be <= 120 characters long  [whitespace/line_length] [5]
Total errors found: 1

**Comment by koolzz** [comment]
@onvm don't sleep on those header prints pls

**Comment by onvm** [comment]
> @onvm don't sleep on those header prints pls

## CI Message

Your results will arrive shortly

**Pull request merged**
