### PR TITLE
[Bug Fix] Add NF Cleanup after Critical Errors

### PR DESCRIPTION
**Pull request by kevindweb**
Speed test had some outstanding errors where we `rte_exit` without cleaning up context

## Summary:
There were a few places where we would exit because of an error after registering the nf with the manager, but didn't clean up properly. This would cause the manager to think the nf was still running, even when it already exited. 

**Usage:**
Speed test, when pcap was enabled, if you input an invalid pcap file, this would break manager. Also, when not enough packets could be created for speed_tester this happens. These are two odd edge cases that we've caught in the past, but didn't remember to verify after changing how we exit NFs. There might be other places, but these were the only other ones I found, and couldn't find other relevant ones in other NFs. 

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                | 👍
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review
 - [ ] Make sure other NFs don't have a similar problem, firewall and scaling, most pertinently 

## Test Plan:
First test that the functionality works and doesn't break on the test cases. Also, I checked if other NFs had similar problems (rte_exit was called but `onvm_nflib_stop(nf_local_ctx)` was not). I did not see any places in other NFs like this, but I might have missed them. Something to keep in mind. 

## Review: 
@koolzz @dennisafa 

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm I fixed it

**Comment by onvm** [comment]
> @onvm I fixed it

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
@onvmTest test this

**Comment by onvmstats** [comment]
@onvmTest again

**Comment by onvmstats** [comment]
@onvmTest data here

**Comment by onvmstats** [comment]
@onvmTest last time rn

**Comment by onvm** [comment]
> @onvmTest last time rn

## CI Message

The current user is true

**Comment by onvm** [comment]
> @onvmTest last time rn

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
@onvmTest will you work

**Comment by onvmstats** [comment]
@onvmTest I should have saved the file

**Comment by onvm** [comment]
> @onvmTest I should have saved the file

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
@onvm no way

**Comment by onvm** [comment]
> @onvm no way

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm testing now

**Comment by onvm** [comment]
> @onvm testing now

## CI Message

Your results will arrive shortly

**Pull request merged**
