### PR TITLE
Manager crash when no ports initialized 

### PR DESCRIPTION
**Pull request by dennisafa**
Manager crashes if we try to send packets out on an uninitialized port.

## Summary:
The function [onvm_pkt_enqueue_port()](https://github.com/dennisafa/openNetVM/blob/port_crash/onvm/onvm_nflib/onvm_pkt_common.c#L260) will call [onvm_pkt_flush_port_queue()](https://github.com/dennisafa/openNetVM/blob/port_crash/onvm/onvm_nflib/onvm_pkt_common.c#L213) which TX bursts packets out of the port with [rte_eth_tx_burst()](https://github.com/dennisafa/openNetVM/blob/port_crash/onvm/onvm_nflib/onvm_pkt_common.c#L226). If you run the manager with no ports and try to do this, it'll segfault on rte_eth_tx_burst(). This fix checks if the port is initialized before sending out packets by adding an array that tracks which ports are initialized. 

**Usage:**
Run manager with `./go.sh 0,1,2,3 0 0xf0 -s stdout -a 0x7f000000000` and basic_monitor with `./go.sh 1 -p 1` then run speed_tester with `./go.sh 2 -d 1` 
It should not crash anymore.

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                | X
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
Follow the usage guide, verify that manager does not crash anymore. 

## Review: 
@koolzz @kevindweb

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
What If you have 1 port enabled and you try to send out of 2?  Looks like this doesn't fix that.

**Comment by koolzz** [comment]
Also slightly concerned about adding a check to the critical path, as this would occur every pkt send (out of the NIC). What does the pktgen perf difference look like on cloudlab nodes?

**Comment by dennisafa** [comment]
> What If you have 1 port enabled and you try to send out of 2? Looks like this doesn't fix that.

hmm, yea good point. what if we initialize all port ID's to NULL before we assign them for a quick check? 
will check out cloudlab perf.

**Comment by dennisafa** [comment]
@onvm give me a run

pktgen is acting up for whatever reason, ill get the # in a bit

**Comment by onvm** [comment]
> @onvm give me a run
> 
> pktgen is acting up for whatever reason, ill get the # in a bit

## CI Message

Your results will arrive shortly

**Comment by dennisafa** [comment]
some pktgen tests from cloudlab
without the extra check:
Screen Shot 2019-08-21 at 4 22 44 PM


with the check:
Screen Shot 2019-08-21 at 4 23 48 PM

no notable performance regressions.

**Comment by kevindweb** [comment]
@dennisafa this works, tested with your solution, and saw that develop does fail with this edge case. Pktgen is fine. My only thought is that it's pretty redundant to keep checking for this port. If an NF has been initialized, the port ID it is trying to access will not change through its life cycle. This means that if the NF tries to get 1 packets, or 1000000 packets, they will all fail. The manager has now wasted the time to check for that port an extra 999,999 times. I hope that makes sense, but there has to be a way to check at initialization of NF if the port is valid (tell it to change if invalid or something), rather than let the NF attempt to enqueue packets forever, consuming resources from manager

**Comment by dennisafa** [comment]
> @dennisafa this works, tested with your solution, and saw that develop does fail with this edge case. Pktgen is fine. My only thought is that it's pretty redundant to keep checking for this port. If an NF has been initialized, the port ID it is trying to access will not change through its life cycle. This means that if the NF tries to get 1 packets, or 1000000 packets, they will all fail. The manager has now wasted the time to check for that port an extra 999,999 times. I hope that makes sense, but there has to be a way to check at initialization of NF if the port is valid (tell it to change if invalid or something), rather than let the NF attempt to enqueue packets forever, consuming resources from manager

the port to be sent out of is defined by the meta->destination value as seen here in [basic_monitor](https://github.com/sdnfv/openNetVM/blob/master/examples/basic_monitor/monitor.c#L171)
i can imagine that NF's may want flexibility with the port that packets are bursted out of.

**Comment by koolzz** [comment]
@dennisafa Code looks good, although as @kevindweb pointed out it is a bunch of extra checks. Can we test with flow lookup disabled macro(I believe its still enabled by default) that should show our best perf ratio comparison. 
If that number is the same then I think we're clear to merge

**Comment by koolzz** [comment]
@onvm

**Comment by onvm** [comment]
> @onvm

## CI Message

Your results will arrive shortly

**Pull request merged**
