### PR TITLE
Update Release notes for 20.05

### PR DESCRIPTION
**Pull request by twood02**
This is the 20.05 release notes.

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by twood02** [comment]
@rohit-mp - can you add yourself to the contributor's list for these release notes?  Thanks!

**Comment by rohit-mp** [comment]
> @rohit-mp - can you add yourself to the contributor's list for these release notes? Thanks!

Thanks! I've created a [PR](https://github.com/sdnfv/openNetVM/pull/215/) for the same.

**Comment by kevindweb** [comment]
@onvm test?

**Comment by onvm** [comment]
> @onvm test?

## CI Message

Your results will arrive shortly

**Pull request merged**
