### PR TITLE
Removed the inline specifier from two functions

### PR DESCRIPTION
**Pull request by gkatsikas**
These specifiers caused compilation problems

### CODE REVIEW

**Comment by twood02** [comment]
@gkatsikas -- can you let us know what compiler you were using and what error it was giving? We haven't seen this issue.

**Comment by gkatsikas** [comment]
My gcc -v gives:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

I guess that even with your compiler, removing these two inline specifiers shouldn't prevent a correct compilation. Is that right?

**Comment by nks5295** [comment]
@twood02 we're using an older version of gcc in our cluster. I have a node with that version installed, I'll see if I can reproduce it.

**Comment by twood02** [comment]
yeah, I see now that it is just removing the inline in the header and leaving it in the c file, so I suspect the behavior is the same either way.  

The compiler generally does a better job than us at picking what to inline anyway so those markers aren't too important.

@nks5295 -- if you can verify this doesn't cause any issues with our version of gcc then you can go ahead and merge.

**Comment by nks5295** [comment]
I have tested that this works with our version of GCC without any problems.  As you said, the new version of the compiler has become "smarter" and enforces better syntax which is why it produces that error.

This is good to merge.

**Comment by twood02** [comment]
thanks @gkatsikas!

**Pull request merged**
