### PR TITLE
cJSON updates

### PR DESCRIPTION
**Pull request by kevindweb**
Our most recent cJSON merge was about 2 years ago.

## Summary:
In 2 years, there have been no API changes that affect our code at all. It compiled on the first time, so I didn't have to touch anything in onvm, only update the lib files. 

**Usage:**
Run regularly to see if cJSON updates break anything. 

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 👍 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review
 - [ ] Find a case where onvm currently can't handle JSON that is fixed in this update

## Test Plan:
pktgen + speed test + etc...

## Review: 
I obviously didn't read all the code, but I tested a bunch of different things to try to break it, including adding an oddly formatted json config file in speed_test. 

(optional) << @-mention people who should review these changes >>
@koolzz @dennisafa if you could make sure everything runs correctly!

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm are we home?

**Comment by onvm** [comment]
> @onvm are we home?

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
@onvm is everything working for unauthorized users?

**Comment by onvmstats** [comment]
@onvm lets try again

**Comment by onvmstats** [comment]
@onvm are you there?

**Comment by onvmstats** [comment]
@onvm what is up

**Comment by onvm** [comment]
> @onvm what is up

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
@onvm one more time to verify

**Comment by onvm** [comment]
> @onvm one more time to verify

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm can you handle more

**Comment by onvm** [comment]
> @onvm can you handle more

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm testing day

**Comment by kevindweb** [comment]
@onvm test again

**Comment by kevindweb** [comment]
@onvm test

**Comment by kevindweb** [comment]
@onvm a

**Comment by kevindweb** [comment]
@onvm again

**Comment by kevindweb** [comment]
@onvm test 2

**Comment by kevindweb** [comment]
@onvm test 3

**Comment by onvm** [comment]
> @onvm test 3

## CI Message

Duplicate request already waiting, ignoring message

**Comment by kevindweb** [comment]
@onvm test 1.5

**Comment by kevindweb** [comment]
@onvm test 3

**Comment by onvm** [comment]
> @onvm test 3

## CI Message

Duplicate request already waiting, ignoring message

**Comment by kevindweb** [comment]
@onvm test 2

**Comment by kevindweb** [comment]
@onvm test 3

**Comment by kevindweb** [comment]
@onvm new handler?

**Comment by kevindweb** [comment]
@onvm cool

**Comment by onvm** [comment]
> @onvm cool

## CI Message

Duplicate request already waiting, ignoring message

**Comment by kevindweb** [comment]
@onvm start up

**Comment by onvm** [comment]
> @onvm test

## CI Message

Another CI run in progress, adding request to the end of the list

**Comment by kevindweb** [comment]
@onvm test ci_queue?

**Comment by onvm** [comment]
> @onvm test ci_queue?

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
Not a comment huh ^, @onvm

**Comment by onvm** [comment]
> Not a comment huh ^, @onvm 
> 

## CI Message

Your results will arrive shortly

**Pull request merged**
