### PR TITLE
Fair Queue NF

### PR DESCRIPTION
**Pull request by Shashwatha-Mitra**
This PR adds a new example - Fair Queue with Round Robin Scheduler

The NF uses the advanced rings mode, classifies IPv4 packets based on the header information, and simulates a round-robin dequeue. 

The CRC32 hash from the DPDK library has been used to classify the packets.

The NF uses a custom implementation of the standard FIFO queuing system. An implementation using the rte_ring structure from the DPDK library failed to scale for large number of queues.
## Summary:

**Usage:** 

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | x
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
An equal number of flows and queues are created to test the NF. The packets are generated by Pktgen and have same headers values except destination port with a 1000B packet size. An example:

fq_test_case resized

A 1G NIC was used to send the packets to the NF. As can be seen from the image, each queue gets approximately 15MBps throughput which is 1/8th of the total link speed.  A maximum of 35% hash collision probability is observed when the NF is tested with a large number of flows and queues (up to 1024). 

**NF Checklist:**

 - [x] Documentation describes purpose of NF, all arguments, and basic usage
 - [x] NF stores all non-global state in a struct referenced by `nf->data` 
 - [x] NF performs initialization in a `function_table->setup` function and frees dynamic memory before exiting

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** @rohit-mp, @NishanthSubramanian, @archit-p, @mohittahiliani

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Aborting, need an authorized user to run CI

**Comment by EthanBaron14** [comment]
@onvm test

**Comment by onvm** [comment]
> @onvm test

## CI Message

Your results will arrive shortly

**Comment by bdevierno1** [comment]
The python lint is a result of the recent [merge](https://github.com/sdnfv/openNetVM/commit/c527955f78a627ed07b1fff33cfc2aaf6c1c4bfe) to develop that has yet been merged into this PR. @kevindweb I'll take a look again sometime soon at how we are using git diff.

**Comment by EthanBaron14** [comment]
Hey, @Shashwatha-Mitra, thanks for working on this! Looks like you found it, but we normally request our PR's onto develop before merging them to master in major releases. This looks pretty good, though! Thanks for contributing!

**Comment by bdevierno1** [comment]
> Hey, @Shashwatha-Mitra, thanks for working on this! Looks like you found it, but we normally request our PR's onto develop before merging them to master in major releases. This looks pretty good, though! Thanks for contributing!

He had already update the branch. Sorry maybe I should have made this clear in the readme. The github actions only gets updated after someone makes a push to an open PR.

**Comment by twood02** [comment]
@Shashwatha-Mitra - I have added a checklist to the bottom of your PR message. Can you verify that you follow all of these and mark them off / fix them as needed?

**Comment by twood02** [comment]
@rohit-mp yes, I think you are correct (this is a general set of questions we will be using for all NFs, so they may not apply in some cases)

**Comment by EthanBaron14** [comment]
@Shashwatha-Mitra one more thing... it looks like you're seeing some errors with the Python linter. After investigating this, it seems that the errors that you're seeing are not present on either the master or develop branches. This leads me to believe you might have an old fork that doesn't have the most recent ONVM release. Please make sure you pull the master branch from the main repo onto your branch. Once you make a commit after that, you should be fine.

**Pull request closed without merging**
