### PR TITLE
Release Note V20.10

### PR DESCRIPTION
**Pull request by WilliamMaa**
<<Replace this line with a short description of the changes>>

## Summary:
Release note for V20.08
**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ X] PR is ready for review

## Review: 
(optional) << @-mention people who should review these changes >>
@dennisafa @twood02 @kevindweb 
(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Aborting, need an authorized user to run CI

**Comment by WilliamMaa** [comment]
@kevindweb @dennisafa can someone resolve the conflicts before they merge this PR. I think it's because Atom automatically deleted some spaces, thank you guys!

**Comment by twood02** [comment]
@WilliamMaa can you put the links to PRs/issues into this? (if you export the Dropbox paper doc to markdown you can easily get them all)

let's also update the version number to 20.10 since that is closer to when this will actually go out.

**Comment by WilliamMaa** [comment]
> @WilliamMaa can you put the links to PRs/issues into this? (if you export the Dropbox paper doc to markdown you can easily get them all)
> 
> let's also update the version number to 20.10 since that is closer to when this will actually go out.

Just updated it!

**Review by dennisafa — DISMISSED** [review]

**Pull request merged**
