### PR TITLE
Update DPDK Script Name in Install Docs

### PR DESCRIPTION
**Pull request by koolzz**
Updates old dpdk script name to the current one.

## Summary:
As noted by @RoyZhang7 the script we had in the Install doc was from old dpdk, this pr updates it.

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
Test in prod

## Review: 
Stamp this please

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 34883723

## Linter Passed

**Comment by koolzz** [comment]
@onvm test

**Comment by onvm** [comment]
> @onvm test

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
@onvm test

**Comment by koolzz** [comment]
@onvm test

**Comment by koolzz** [comment]
@onvm test

**Comment by koolzz** [comment]
@onvm q

**Comment by koolzz** [comment]
@onvm refusal

**Comment by koolzz** [comment]
@onvm qqq

**Comment by koolzz** [comment]
@onvm qqq

**Comment by onvm** [comment]
> @onvm qqq

## CI Message

User not authorized to run CI, please contact one of the repo maintainers

**Comment by koolzz** [comment]
q @onvm

**Comment by onvm** [comment]
> q @onvm

## CI Message

User not authorized to run CI, please contact one of the repo maintainers

**Comment by koolzz** [comment]
@onvm q

**Comment by koolzz** [comment]
@onvm qqq

**Comment by koolzz** [comment]
@qqq

**Comment by koolzz** [comment]
@onvm qqq

**Comment by onvm** [comment]
> @onvm qqq

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
@onvm hello

**Comment by koolzz** [comment]
@onvm twice in a row?

**Comment by onvm** [comment]
> @onvm twice in a row?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm twice in a row?

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 34773845

## Linter Passed

**Comment by RoyZhang7** [comment]
Lol, never know CI would be dumb.

**Comment by koolzz** [comment]
> Lol, never know CI would be dumb.

Was testing some encryption/logging updates 😄

**Comment by koolzz** [comment]
Can you approve the pr @RoyZhang7?

**Pull request merged**
