### PR TITLE
Enforce 120 line length in linter

### PR DESCRIPTION
**Pull request by koolzz**
The linter wasn't properly updated with the latest line length and didn't report the errors.

## Summary:
 - Elevated the line length limit error as we're only handling messages of level(5) right now.
 - Changed config to use line length of 120

**Usage:**
CI please verify this

## Review: 
Anyone

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35605770

## Linter Failed

examples/aes_decrypt/aes.c:78:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:283:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:306:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:331:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:371:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:394:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:404:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:431:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:467:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:468:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:478:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:506:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:515:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:519:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:523:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_decrypt/aes.c:535:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aes.c:1024:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_decrypt/aes.c:1028:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_decrypt/aes.c:1081:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_decrypt/aes.c:1087:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Total errors found: 20
examples/aes_decrypt/aesdecrypt.c:93:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_decrypt/aesdecrypt.c:180:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 2
examples/aes_encrypt/aes.c:78:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:283:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:306:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:331:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:371:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:394:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:404:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:431:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:467:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:468:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:478:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:506:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:515:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:519:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:523:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_encrypt/aes.c:535:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aes.c:1024:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_encrypt/aes.c:1028:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_encrypt/aes.c:1081:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/aes_encrypt/aes.c:1087:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Total errors found: 20
examples/aes_encrypt/aesencrypt.c:93:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/aes_encrypt/aesencrypt.c:180:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 2
examples/arp_response/arp_response.c:85:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:137:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:144:  Missing space before ( in switch(  [whitespace/parens] [5]
examples/arp_response/arp_response.c:148:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:164:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:195:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:263:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:276:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:279:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/arp_response/arp_response.c:280:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 10
examples/basic_monitor/monitor.c:82:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/basic_monitor/monitor.c:84:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/basic_monitor/monitor.c:164:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 3
examples/bridge/bridge.c:76:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/bridge/bridge.c:135:  Missing space before ( in if(  [whitespace/parens] [5]
examples/bridge/bridge.c:138:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/bridge/bridge.c:146:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/bridge/bridge.c:156:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Total errors found: 5
examples/flow_table/flow_table.c:103:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/flow_table.c:155:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_table/flow_table.c:198:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/flow_table.c:209:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_table/flow_table.c:216:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/flow_table.c:224:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/flow_table.c:231:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/flow_table.c:238:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/flow_table.c:240:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 9
examples/flow_table/msgbuf.c:71:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:73:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:83:  Missing space before ( in while(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:86:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:89:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:106:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:108:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:116:  Missing space before ( in while(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:119:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:125:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:138:  Extra space before last semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
examples/flow_table/msgbuf.c:140:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:149:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:157:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:159:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:162:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/msgbuf.c:169:  Missing space before ( in while(  [whitespace/parens] [5]
Total errors found: 17
examples/flow_table/sdn.c:99:  Extra space before last semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
examples/flow_table/sdn.c:125:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:127:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:147:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/sdn.c:147:  Missing space before {  [whitespace/braces] [5]
examples/flow_table/sdn.c:153:  Missing space before ( in while(  [whitespace/parens] [5]
examples/flow_table/sdn.c:160:  Missing space before {  [whitespace/braces] [5]
examples/flow_table/sdn.c:235:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/sdn.c:239:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/sdn.c:247:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_table/sdn.c:279:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:281:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_table/sdn.c:293:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_table/sdn.c:418:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:423:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:493:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/sdn.c:501:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_table/sdn.c:538:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:542:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:545:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:547:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:555:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/sdn.c:569:  Missing space before ( in while(  [whitespace/parens] [5]
Total errors found: 23
examples/flow_table/setupconn.c:82:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:89:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:94:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:102:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:110:  Missing space before {  [whitespace/braces] [5]
examples/flow_table/setupconn.c:112:  Missing space before {  [whitespace/braces] [5]
examples/flow_table/setupconn.c:122:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:140:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:149:  Missing space before ( in if(  [whitespace/parens] [5]
examples/flow_table/setupconn.c:156:  Missing space before ( in if(  [whitespace/parens] [5]
Total errors found: 10
examples/flow_tracker/flow_tracker.c:108:  Missing space before ( in switch(  [whitespace/parens] [5]
examples/flow_tracker/flow_tracker.c:112:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_tracker/flow_tracker.c:133:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_tracker/flow_tracker.c:204:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_tracker/flow_tracker.c:210:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
examples/flow_tracker/flow_tracker.c:286:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/flow_tracker/flow_tracker.c:295:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 7
examples/load_balancer/load_balancer.c:138:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_balancer/load_balancer.c:217:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_balancer/load_balancer.c:348:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_balancer/load_balancer.c:355:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_balancer/load_balancer.c:491:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 5
examples/load_generator/load_generator.c:112:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_generator/load_generator.c:116:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_generator/load_generator.c:166:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_generator/load_generator.c:179:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/load_generator/load_generator.c:230:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 5
examples/nf_router/nf_router.c:90:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/nf_router/nf_router.c:145:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/nf_router/nf_router.c:149:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/nf_router/nf_router.c:217:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/nf_router/nf_router.c:226:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/nf_router/nf_router.c:230:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 6
examples/scaling_example/scaling.c:120:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:138:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:149:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:170:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:197:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:264:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:275:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:277:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:300:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/scaling_example/scaling.c:312:  Missing space before ( in while(  [whitespace/parens] [5]
Total errors found: 10
examples/simple_forward/forward.c:80:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/simple_forward/forward.c:158:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 2
examples/speed_tester/speed_tester.c:126:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/speed_tester/speed_tester.c:127:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/speed_tester/speed_tester.c:266:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/speed_tester/speed_tester.c:279:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/speed_tester/speed_tester.c:343:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/speed_tester/speed_tester.c:453:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 6
examples/test_flow_dir/test_flow_dir.c:87:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
examples/test_flow_dir/test_flow_dir.c:158:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 2
onvm/onvm_mgr/main.c:98:  Mismatching spaces inside () in while  [whitespace/parens] [5]
onvm/onvm_mgr/main.c:121:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/main.c:130:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/main.c:207:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/main.c:297:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/main.c:300:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 6
onvm/onvm_mgr/onvm_args.c:166:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_mgr/onvm_args.c:166:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_mgr/onvm_args.c:172:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_mgr/onvm_args.c:172:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_mgr/onvm_args.c:194:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_args.c:197:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_args.c:198:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_args.c:199:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_args.c:328:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_mgr/onvm_args.c:352:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_mgr/onvm_args.c:357:  Missing space before ( in if(  [whitespace/parens] [5]
Total errors found: 11
onvm/onvm_mgr/onvm_init.c:170:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:178:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:188:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:205:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:211:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:222:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_mgr/onvm_init.c:326:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_init.c:339:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 8
onvm/onvm_mgr/onvm_nf.c:182:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_mgr/onvm_nf.c:255:  Missing space before ( in if(  [whitespace/parens] [5]
Total errors found: 2
onvm/onvm_mgr/onvm_stats.c:150:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:183:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_mgr/onvm_stats.c:183:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_mgr/onvm_stats.c:307:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:341:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:420:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:421:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:427:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:431:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:433:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_mgr/onvm_stats.c:487:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 11
onvm/onvm_nflib/onvm_config_common.c:52:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_config_common.c:112:  Missing space before ( in for(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_config_common.c:112:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_config_common.c:171:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:323:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:332:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:344:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:354:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:361:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:417:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:433:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:468:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_config_common.c:487:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
Total errors found: 13
onvm/onvm_nflib/onvm_flow_dir.c:64:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_flow_dir.c:95:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:103:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:111:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:128:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:143:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:151:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:159:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_flow_dir.c:176:  Missing space before {  [whitespace/braces] [5]
Total errors found: 9
onvm/onvm_nflib/onvm_nflib.c:169:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_nflib.c:341:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:344:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:347:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:351:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:354:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:357:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:443:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_nflib.c:552:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_nflib.c:584:  Missing space before ( in switch(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:743:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:754:  Missing space before ( in if(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_nflib.c:821:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_nflib.c:822:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_nflib.c:830:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 15
onvm/onvm_nflib/onvm_pkt_common.c:96:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_common.c:186:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 2
onvm/onvm_nflib/onvm_pkt_helper.c:59:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:155:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:171:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:177:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:272:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:279:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:294:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:296:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:313:  Missing space before ( in switch(  [whitespace/parens] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:371:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:376:  Missing space before {  [whitespace/braces] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:407:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:470:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
onvm/onvm_nflib/onvm_pkt_helper.c:483:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 14
onvm/onvm_nflib/onvm_sc_common.c:83:  Lines should be <= 100 characters long  [whitespace/line_length] [5]
Total errors found: 1

**Comment by koolzz** [comment]
@onvm check again

**Comment by onvm** [comment]
> @onvm check again

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm check again

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35147720

## Linter Failed

examples/speed_tester/speed_tester.c:364:  Lines should be <= 120 characters long  [whitespace/line_length] [5]
Total errors found: 1
onvm/onvm_mgr/main.c:109:  Lines should be <= 120 characters long  [whitespace/line_length] [5]
Total errors found: 1

**Comment by koolzz** [comment]
@onvm CI do your thing

**Comment by onvm** [comment]
> @onvm CI do your thing

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm CI do your thing

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35182769

## Linter Failed

onvm/onvm_mgr/main.c:109:  Lines should be <= 120 characters long  [whitespace/line_length] [5]
Total errors found: 1

**Comment by koolzz** [comment]
@onvm how about now

**Comment by onvm** [comment]
> @onvm how about now

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm how about now

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35149918

## Linter Passed

**Comment by koolzz** [comment]
@rskennedy, @kevindweb, @dennisafa Can anyone stamp this? (For CI to check line length the PRs need to pull this change)

pls

**Comment by koolzz** [comment]
@onvm how do those .h files look

**Comment by onvm** [comment]
> @onvm how do those .h files look

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm how do those .h files look

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35141079

## Linter Passed

**Pull request merged**
