### PR TITLE
Updated README.md with description of config file.

### PR DESCRIPTION
**Pull request by khaledshahine**
<<Replace this line with a short description of the changes>>

## Summary:

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Aborting, need an authorized user to run CI

**Comment by kevindweb** [comment]
@onvm approval?

**Comment by kevindweb** [comment]
@onvm awake?

**Comment by onvm** [comment]
> @onvm awake?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm awake?

## CI Message

Error: Failed to copy ONVM files to nimbnode23

**Comment by kevindweb** [comment]
@this time

**Comment by kevindweb** [comment]
@onvm this time

**Comment by onvm** [comment]
> @onvm this time

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm this time

## CI Message

Error: Failed to copy ONVM files to nimbnode23

**Comment by kevindweb** [comment]
@onvm try again

**Comment by twood02** [comment]
Thanks @khaledshahine for this documentation update!

@kevindweb - this PR is really only trying to modify one line of documentation: https://github.com/sdnfv/openNetVM/pull/241/commits/76fdd24d24adbefae74faee09eae460cdf37ec8e
the other commits are because of repo differences I think.  Can you figure out the git magic to clean this up so it only has the single relevant commit?

**Comment by kevindweb** [comment]
@tim the problem I think is he made the PR to master, so I think it's tracking that. The only thing I can think to do is for me (or @khaledshahine) to make a commit that merges develop's changes back into this branch `git pull upstream/develop && git push`, resetting all the "changes" so we should only see the one line change.

**Comment by twood02** [comment]
@EthanBaron14 will try to clean up this branch so we can merge

**Comment by EthanBaron14** [comment]
I looked into this, but unfortunately I don't have access to push onto someone else's branch. Since the `docs/Install.md` and the `onvm/go.sh` files weren't changed in this PR, I'd recommend just copy/pasting the contents of the versions of those files existing on the `develop` branch into this branch to fix the merge conflicts.

**Comment by kevindweb** [comment]
Pretty sure this should be closed from #258

**Pull request closed without merging**
