### PR TITLE
DPDK 20.05, Pktgen 20.03 updates for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by sreyanalla**
This PR builds on @[Vivek-anand-jain](https://github.com/Vivek-anand-jain) 's DPDK version update PR (#231 ). Adds to the resolution for issue #226 .

Specifically:
- Resolves pktgen build issues (mentioned in comments of #231) by updating Pktgen submodule to [dpdk-pktgen v20.03](https://git.dpdk.org/apps/pktgen-dpdk/tag/?h=pktgen-20.03.0)
- Changes so ONVM with DPDK 20.05 can run on Ubuntu 20.04

A CloudLab profile has been created using this branch: [ONVM20-U20](https://www.cloudlab.us/show-profile.php?uuid=442df756-cc7a-11ea-b1eb-e4434b2381fc)

**Note** that you may run into the following errors/warnings:
- When syncing/updating dpdk submodules
```
dpkg: unrecoverable fatal error, aborting
syntax error: unknown group "mlocate" in statoverride file,
  E: sub-process /usr/bin/dpkg returned an error code (2)
```
**Solution**:  run` sudo sed -i '/mlocate/d ' /var/lib/dpkg/statoverride`
- When running the install script:
```
/usr/bin/env: python : No such file or directory 
```
**Solution**: run `sudo ln -s /usr/bin/python3 /usr/bin/python`

**_If the above issues seem to persist/appear to occur every time, please let me know in the comments and I can make changes to scripts where necessary in order to prevent them beforehand._**

**Usage:**
Follows same general usage protocol for ONVM

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          | #226  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       |  updates Pktgen version, uses newer version of Ubuntu 20.04
| Web stats updates        | 

## Merging notes:
 - Dependencies: Ubuntu 20.04  
PR #231 will need to be merged prior to this PR.

**TODO before merging :**
 - [X] PR is ready for review

## Test Plan:
- Run manager, NFs as usual 
- Test using pktgen (ensure that pktgen is able to build and run smoothly)

## Review: 
@catherinemeadows @EthanBaron14

### CODE REVIEW

**Comment by catherinemeadows** [comment]
Instantiated the 1 node setup and didn't run into any of the errors that you mentioned. I was able to successfully run various NFs as well was startup chains of NFs. I'm not sure how frequently the errors that you mentioned might occur. It might be worth doing a fix if it's something that kept coming up for you/others. 

Ethan and I are still trying to get a multiple node setup on Cloud Lab to test PktGen...resources seem low at the moment and the c220g5 multiple node setup failed earlier because it didn't have the correct number of hardware ports available.

**Comment by EthanBaron14** [comment]
Exactly what Cat said. I created a reservation on c220g5 earlier today to start at 10. Since then, it says that there's only one node being "Used" out of the three I requested. When I tried to instantiate the new ONVM profile that supports multiple nodes, CloudLab failed after the "Provisioning" step. It said there weren't enough hardware devices on `node2` to accommodate the request. The number available was 1 and the number required was 2. This leads me to believe that the c220g5 nodes don't have enough NICs to run the three-node topology.

Accordingly, I updated my reservation to request three c220g1 nodes that should be available later tonight. I'll try to instantiate the profile again in the morning.

**Comment by EthanBaron14** [comment]
Tested all of this using one node on the c220g1 cluster. Following the installation instructions outlined in the CloudLab profile enabled me to build and run the manager and NFs without any issues. I was able to build and run ONVM and NFs after running those three commands in the profile instructions and binding the gigabit NICs to DPDK. However, it's worth noting is that running the install script (`scripts/install.sh`) is not required and actually makes it so ONVM does NOT run without manual configuration or running those three setup commands again.

I still want to test this with the three-node configuration, which might be possible when some nodes free up on the c220g1 cluster just after midnight. I'll try to reserve three nodes for testing at that time but likely won't be able to test until the morning after our meeting.

**Comment by dennisafa** [comment]
I feel like we should just do the DPDK checkout within the install script, and add the one-line solutions in there as well. Less stress on the user.

**Pull request merged**
