### PR TITLE
Dependabot ONVM Web Updates

### PR DESCRIPTION
**Pull request by kevindweb**
Onvm_web versioning updates from dependabot.

## Summary:
I needed to manually build the new react app for onvm_web given the updated versions, which has to change a few of the `onvm_web/web-build` files. Luckily I made a minifying script last time that can build everything so it worked like a charm!

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues/PR          | Pull Request #165 
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 👍 
| Web stats updates        | 👍 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [X] PR is ready for review

## Test Plan:
Ignore dependabot's pull request, because its commit is included here. 

## Review: 
@koolzz or @dennisafa if you want to run it to test, if not that's fine because it doesn't touch any of the onvm code at all which is nice 👍

### CODE REVIEW

**Comment by kevindweb** [comment]
@onvm can you run?

**Comment by onvm** [comment]
> @onvm can you run?

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
Merged all other dependencies, tested and packaged the web app. It all seems to be working.

**Comment by kevindweb** [comment]
@onvm show me what you got

**Comment by onvm** [comment]
> @onvm show me what you got

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> Testing PAT

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm time to test the tokens

**Comment by onvm** [comment]
> @onvm time to test the tokens

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
@kevindweb this is good to merge right

**Comment by kevindweb** [comment]
I just merged the final web update. I verified it worked and didn't break. Minifying the updates made sure there weren't too many line changes.

**Comment by kevindweb** [comment]
Once we merge this @koolzz please go ahead and delete the pull requests from dependabot. I have merged all of their suggestions into this one so they will be useless.

**Comment by kevindweb** [comment]
@onvm can you review one last time

**Comment by onvm** [comment]
> @onvm can you review one last time

## CI Message

Your results will arrive shortly

**Pull request merged**
