### PR TITLE
Update Extra Verbose Stats Display

### PR DESCRIPTION
**Pull request by koolzz**
The Extra Verbose stats display was missing a few of the new stats (parent_id, children_cnt, state was printed as int not a char). This pr fixes both the verbose stats header and the verbose stats output.

@kevindweb does this look good?

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
@onvm again

**Comment by onvm** [comment]
> @onvm again

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
Also added the descriptions of stats output in the README.md for onvm/

**Pull request merged**
