### PR TITLE
Clang-format global style fix

### PR DESCRIPTION
**Pull request by koolzz**
Fix all the formatting issues !

## Summary:
Slightly modified the Google format style and applied to all code.
Broke all the changes into chunks, see commits.

Also most of the changes are from the `aes_encrypt` or `aes_derypt` or `flow_table` NFs, so don't be too scared by the number of line changes.

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
Oh boy, how do we test this

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Error: ERROR: Failed to fetch results from nimbnode30


## Linter Failed

examples/flow_table/sdn.c:141:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Total errors found: 1
onvm/onvm_mgr/onvm_init.c:218:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
Total errors found: 1
onvm/onvm_mgr/onvm_stats.c:360:  Line contains only semicolon. If this should be an empty statement, use {} instead.  [whitespace/semicolon] [5]
Total errors found: 1
onvm/onvm_nflib/onvm_config_common.c:418:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:434:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:489:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
Total errors found: 3
onvm/onvm_nflib/onvm_nflib.c:549:  If an else has a brace on one side, it should have it on both  [readability/braces] [5]
Total errors found: 1

**Comment by koolzz** [comment]
Hm some linking broke, maybe .h file ordering

**Comment by koolzz** [comment]
@onvm again!

**Comment by onvm** [comment]
> @onvm again!

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm again!

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35162001

## Linter Failed

onvm/onvm_mgr/onvm_init.c:218:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
Total errors found: 1
onvm/onvm_nflib/onvm_config_common.c:418:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:434:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
onvm/onvm_nflib/onvm_config_common.c:489:  Never use sprintf. Use snprintf instead.  [runtime/printf] [5]
Total errors found: 3

**Comment by koolzz** [comment]
@onvm  how is the linter looking

**Comment by onvm** [comment]
> @onvm  how is the linter looking

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm  how is the linter looking

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35158412

## Linter Passed

**Comment by koolzz** [comment]
@nks5295 thoughts on merging this?

**Comment by koolzz** [comment]
> Fix the merge conflicts

Niceeee, linter will no longer be a page long. Will fix soon

**Comment by koolzz** [comment]
@onvm still good to go?

**Comment by onvm** [comment]
> @onvm still good to go?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm still good to go?

## CI Message

Run successful see results:
[Results from nimbnode30]
Median TX pps for Speed Tester: 35230887

## Linter Passed

**Pull request merged**
