### PR TITLE
Update Pktgen submodule pointer to the 3.6.5 version

### PR DESCRIPTION
**Pull request by koolzz**
Updates the pktgen version to fix make issues.

## Summary:
Update the pktgen branch pointer

**Usage:**
Run pktgen

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       |  :+1: 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
Should be good

## Review: 
@rskennedy  pls test if it doesn't break

### CODE REVIEW

**Comment by twood02** [comment]
### Review checklist:  

- Sanity checks, assigned to @rskennedy @dennisafa 
    - Run make in `/onvm` and `/examples` directories
    - Test new functionality or bug fix from the pr (if needed)

- Documentation, assigned to @rskennedy @dennisafa 
    - Check if the new changes are well documented, in both code and READMEs

**Comment by rskennedy** [comment]
Ran through the instructions on cloudlab nodes, pktgen works as expected. Was able to send some packets back and forth.

**Comment by rskennedy** [comment]
Should we have a line in the readme with some basic commands? i.e. start all and how to set mac addr

**Comment by koolzz** [comment]
@rskennedy added, approve if all good

**Pull request merged**
