### PR TITLE
Skeleton NF Functionality Improvements

### PR DESCRIPTION
**Pull request by jettjacobs**
## Summary:
Changes Resolved From #312 

Additional Functionality:
- Additional Command-Line Arguments
- Timer-based or Packet-based print delays

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   | 
| Bug fixes                |
| New functionality        | X
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  X
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review

## Test Plan:
- Run NF on the manager
- Use speed_tester to send packets to skeleton
- Ensure that the skeleton NF can correctly print the number of packets. Test timer-based (-p) delays and packet-based delays (-v).

## Review: 
Review comments to confirm validity
Command-line arguments should be mutually exclusive

### CODE REVIEW

**Comment by dennisafa** [comment]
Did you want to close this PR and make your updates as a new commit to your previous PR?  Otherwise, could you close the other PR out?

**Comment by jettjacobs** [comment]
@dennisafa I will close out the other PR, thanks! I created a new PR to pull from my own forked develop branch, rather than master.

**Review by dennisafa — DISMISSED** [review]
LGTM, just resolve conflicts.

**Comment by jettjacobs** [comment]
@dennisafa sorry about dismissing the review, I had to make one more adjustment. Merge conflicts are now resolved

**Review by twood02 — APPROVED** [review]
lgtm

**Comment by twood02** [comment]
@catherinemeadows sometime when I am not around, could you do a meeting where you show the summer students how you would test and eventually approve this PR? That would be good for them to see.

**Comment by catherinemeadows** [comment]
> @catherinemeadows sometime when I am not around, could you do a meeting where you show the summer students how you would test and eventually approve this PR? That would be good for them to see.

Yep, will do!

**Pull request merged**
