### PR TITLE
Improve usability of cloudlab profiles

### PR DESCRIPTION
**Pull request by WilliamMaa**
This PR relates to issue #262. I fixed some documentation issues, and improved general usability of onvm.

## Summary:
1. Now you can compile everything in the root directory instead of compiling dpdk, manager and examples separately.
2. For cloudlab profiles, you only need to run setup_cloudlab.sh to setup all the environmental variables and do the environment setup.
**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          | #262 
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   | X
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [X] PR is ready for review

## Test Plan:
Try doing a make in a Ubuntu 20 environment under the root directory, see if it can correctly make everything.
On cloudlab profiles, run setup_cloudlab.sh see if it correctly does the setup.

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Aborting, need an authorized user to run CI

**Review by twood02 — APPROVED** [review]

**Comment by twood02** [comment]
These changes look good to me.  @kevindweb or @dennisafa will one of you be able to double check this and then merge it?  We would like these changes merged into master soon so we can update the cloudlab profile.

**Comment by WilliamMaa** [comment]
I think it is better that we do not include making dpdk in the root Makefile, I think dpdk's build is a little complicated than I imagined.

**Review by kevindweb — APPROVED** [review]
@WilliamMaa I tested this, it works pretty well so that's awesome! I got it started up on the ubuntu 20 cloud lab profile very quickly

**Comment by kevindweb** [comment]
@onvm sanity

**Comment by onvm** [comment]
> @onvm sanity

## CI Message

Your results will arrive shortly

**Review by onvm — APPROVED** [review]
> @onvm sanity

## CI Message

Run successful see results:
Test took: 15 minutes, 55 seconds
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Test performance check passed

[Results from nimbnode23]

 - Median TX pps for Pktgen: 7743546                      
  Performance rating - 100.57% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 41084717                      
  Performance rating - 97.82% (compared to 42000000 average)

**Review by dennisafa — APPROVED** [review]

**Comment by twood02** [comment]
@dennisafa when you have a chance, please sync this to master too (you don't need to make a full release).

**Pull request merged**
