### PR TITLE
Warn user when not specifying -m flag in start_nf.sh

### PR DESCRIPTION
**Pull request by dennisafa**
Warn the user if -m isn't specified in start_nf.sh 

## Summary:
You can bind a core manually using -l and -m in the start_nf script. If -m isn't specified, no binding will occur. This change will let the user know that they should supply this flag if they want the binding to occur. 
**Usage:**
Run any NF using the `./start_nf.sh NF-NAME DPDK_ARGS -- ONVM_ARGS -- NF_ARGS` format
(i.e, `./start_nf.sh speed_tester -l 5 -- -m -r 3 -- -d 2` where is -l is the core # to assign, and -m is the binding flag)

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  X
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [x] PR is ready for review

## Test Plan:
Run the start_nf script without and with the -m flag.

## Review: 
@koolzz @kevindweb

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by koolzz** [comment]
Lgtm, testing is on you though. I like @kevindweb nit looks elegant

**Comment by dennisafa** [comment]
> I think it looks good, really just a bash nit, and Nick can dispute, but personally I like combining those conditions, as well as using built-in regex.
> `[[ $DPDK_ARGS =~ "-l" && ! $ONVM_ARGS =~ "-m" ]]`

looks clean!

**Comment by kevindweb** [comment]
@onvm I will test, but please work correctly

**Comment by onvm** [comment]
> @onvm I will test, but please work correctly

## CI Message

Your results will arrive shortly

**Pull request merged**
