### PR TITLE
Installation Guide was Improved

### PR DESCRIPTION
**Pull request by 1995parham**
I have tried to correct links in Installation Guide and improve some shell commands' syntax highlighting.

### CODE REVIEW

**Comment by twood02** [comment]
Thanks Parham! This looks good to me.  @nks5295 please double check and merge.

**Comment by twood02** [comment]
@1995parham - it looks like docs/Examples.md also has a broken link for the corehelper script.... can you fix that too for this PR? Thanks!

**Comment by 1995parham** [comment]
@twood02 I will fix it now

**Comment by nks5295** [comment]
This looks good to me too. I'll merge it.

**Pull request merged**
