### PR TITLE
Update README.md with description of config file.

### PR DESCRIPTION
**Pull request by WilliamMaa**
This PR is made to resolve the linter problem in PR #241
The original PR is made by @khaledshahine

## Summary:

**Usage:**

| This PR includes         |          |
| ------------------------ | -------- |
| Resolves issues          |  
| Breaking API changes     |
| Internal API changes     |
| Usability improvements   |  
| Bug fixes                |
| New functionality        |
| New NF/onvm_mgr args     | 
| Changes to starting NFs  |  
| Dependency updates       | 
| Web stats updates        | 

## Merging notes:
 - Dependencies: None  

**TODO before merging :**
 - [ ] PR is ready for review

## Review: 
(optional) << @-mention people who should review these changes >>

(optional) **Subscribers:** << @-mention people who probably care about these changes >>

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Aborting, need an authorized user to run CI

**Review by dennisafa — COMMENTED** [review]
I don't see an issue with the current language..but I won't complain if I'm overruled. If you're going to change this bit then please change this to make us consistent.  https://github.com/sdnfv/openNetVM/blob/master/examples/nf_router/nf_router.c#L85

**Comment by WilliamMaa** [comment]
@dennisafa The original PR #241 had the linter problem, I think it was because @khaledshahine tried to PR it into a wrong branch? I just copied what he did in that PR and see if this could resolve that issue.

**Review by dennisafa — APPROVED** [review]

**Review by kevindweb — APPROVED** [review]
Looks good to me👍

**Pull request merged**
